# Generated by Django 3.2 on 2021-05-01 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_house_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name', 'price'], 'verbose_name': 'дом', 'verbose_name_plural': 'дома'},
        ),
    ]
